---
kind: pipeline
type: docker
name: x86_64-linux
platform:
  os: linux
  arch: amd64
workspace:
  path: /workspace

steps:
- name: probe
  image: ci/debian-amd64:11.1-2
  commands:
  - ./ci/zinc/linux_probe.sh

- name: build
  image: ci/debian-amd64:11.1-2
  commands:
  - ./ci/zinc/linux_build.sh

- name: test
  depends_on:
  - build
  image: ci/debian-amd64:11.1-2
  commands:
  - ./ci/zinc/linux_test.sh

- name: package
  depends_on:
  - test
  when:
    branch:
      - master
    event:
      - push
  image: ci/debian-amd64:11.1-2
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
  - ./ci/zinc/linux_package.sh

---
kind: pipeline
type: docker
name: on-master-success
platform:
  os: linux
  arch: amd64
workspace:
  path: /workspace
depends_on:
- x86_64-linux
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: on-master-sucess
  image: ci/debian-amd64:11.1-2
  environment:
    SRHT_OAUTH_TOKEN:
      from_secret: SRHT_OAUTH_TOKEN
  commands:
  - ./ci/zinc/linux_on_master_sucess.sh
