jobs:
- job: BuildMacOS
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 360
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/macos_script
    name: main
    displayName: 'Build and test'
- job: BuildMacOS_arm64
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 180
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/macos_arm64_script
    name: main
    displayName: 'Build'
- job: BuildWindows
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 360
  steps:
  - powershell: |
      (New-Object Net.WebClient).DownloadFile("https://github.com/msys2/msys2-installer/releases/download/2021-07-25/msys2-base-x86_64-20210725.sfx.exe", "sfx.exe")
      .\sfx.exe -y -o\
    displayName: Download/Extract/Install MSYS2
  - script: |
      @REM install updated filesystem package first without dependency checking
      @REM because of: https://github.com/msys2/MSYS2-packages/issues/2021
      %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Sydd filesystem"
    displayName: Workaround filesystem dash MSYS2 dependency issue
  - script: |
      %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
      %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
    displayName: Update MSYS2
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/windows_msvc_script.bat
    name: main
    displayName: 'Build and test'
- job: OnMasterSuccess
  dependsOn:
  - BuildMacOS
  - BuildMacOS_arm64
  - BuildWindows
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  strategy:
    maxParallel: 1
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    version: $[ dependencies.BuildMacOS.outputs['main.version'] ]
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: oauth_token
  - script: ci/azure/on_master_success
    displayName: 'master branch success hook'
