#!/bin/sh

set -x
set -e

pacman -S --needed --noconfirm wget zip python3-pip
pip install s3cmd
wget "https://ziglang.org/deps/llvm%2bclang-8.0.0-win64-msvc-release.tar.xz"
tar xf llvm+clang-8.0.0-win64-msvc-release.tar.xz
