#!/bin/sh

set -x
set -e

pacman -Suy --needed --noconfirm
pacman -S --needed --noconfirm cmake git ninja wget p7zip python3-pip tar xz

pip install s3cmd

ZIGDIR="$(pwd)"
CACHE_BASENAME="zig+llvm+lld+clang-x86_64-windows-gnu-0.8.0-dev.1951+c59241bda"
PREFIX="$HOME/$CACHE_BASENAME"
ZIG="$PREFIX/bin/zig.exe"

cd "$HOME"
wget -nv "https://ziglang.org/deps/$CACHE_BASENAME.tar.xz"
tar xf "$CACHE_BASENAME.tar.xz"

cd "$ZIGDIR"

# Make the `zig version` number consistent.
# This will affect the cmake command below.
git config core.abbrev 9
git fetch --unshallow || true
git fetch --tags

mkdir build
cd build
"$ZIG" build -Dstage1 -Domit-stage2 -Drelease \
    -Dtarget=x86_64-windows-gnu \
    -Dcpu=x86_64_v2 \
    --search-prefix "$PREFIX" \
    --override-lib-dir "$ZIGDIR/lib" \
    --prefix "$(pwd)/dist"

dist/bin/zig.exe build test-behavior -Dskip-non-native
# Disabled to prevent OOM
# dist/bin/zig build test-stage2
dist/bin/zig.exe build test-fmt -Dskip-non-native
dist/bin/zig.exe build test-std -Dskip-non-native
dist/bin/zig.exe build test-compiler-rt -Dskip-non-native
dist/bin/zig.exe build test-compare-output -Dskip-non-native
dist/bin/zig.exe build test-standalone -Dskip-non-native
dist/bin/zig.exe build test-stack-traces -Dskip-non-native
dist/bin/zig.exe build test-cli -Dskip-non-native
dist/bin/zig.exe build test-asm-link -Dskip-non-native
dist/bin/zig.exe build test-runtime-safety -Dskip-non-native
dist/bin/zig.exe build test-translate-c -Dskip-non-native
dist/bin/zig.exe build test-run-translated-c -Dskip-non-native
dist/bin/zig.exe build docs

if [ "${BUILD_REASON}" != "PullRequest" ]; then
  cd "$ZIGDIR/build"

  mv ../LICENSE dist/
  mv ../zig-cache/langref.html dist/
  mv dist/bin/zig.exe dist/
  rmdir dist/bin

  VERSION=$(dist/zig.exe version)
  DIRNAME="zig-windows-x86_64-$VERSION"
  TARBALL="$DIRNAME.zip"
  mv dist "$DIRNAME"
  7z a "$TARBALL" "$DIRNAME"

  # mv "$DOWNLOADSECUREFILE_SECUREFILEPATH" "$HOME/.s3cfg"
  s3cmd -c "$DOWNLOADSECUREFILE_SECUREFILEPATH" put -P --add-header="cache-control: public, max-age=31536000, immutable" "$TARBALL" s3://ziglang.org/builds/

  SHASUM=$(sha256sum $TARBALL | cut '-d ' -f1)
  BYTESIZE=$(wc -c < $TARBALL)

  JSONFILE="windows-$GITBRANCH.json"
  touch $JSONFILE
  echo "{\"tarball\": \"$TARBALL\"," >>$JSONFILE
  echo "\"shasum\": \"$SHASUM\"," >>$JSONFILE
  echo "\"size\": \"$BYTESIZE\"}" >>$JSONFILE

  s3cmd -c "$DOWNLOADSECUREFILE_SECUREFILEPATH" put -P --add-header="Cache-Control: max-age=0, must-revalidate" "$JSONFILE" "s3://ziglang.org/builds/$JSONFILE"
  s3cmd -c "$DOWNLOADSECUREFILE_SECUREFILEPATH" put -P "$JSONFILE" "s3://ziglang.org/builds/x86_64-windows-$VERSION.json"

  # `set -x` causes these variables to be mangled.
  # See https://developercommunity.visualstudio.com/content/problem/375679/pipeline-variable-incorrectly-inserts-single-quote.html
  set +x
  echo "##vso[task.setvariable variable=tarball;isOutput=true]$TARBALL"
  echo "##vso[task.setvariable variable=shasum;isOutput=true]$SHASUM"
  echo "##vso[task.setvariable variable=bytesize;isOutput=true]$BYTESIZE"
fi
