name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        A bug is when something works differently than it is expected to.
  - type: checkboxes
    id: searched
    attributes:
      label: Remember to search before filing a new report
      options:
        - label: I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.
          required: true
  - type: input
    id: version
    attributes:
      label: Zig Version
      description: "The output of `zig version`"
      placeholder: "0.9.0-dev.1275+ac52e0056"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: What exactly can someone else do, in order to observe the problem that you observed?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happened instead? Be sure to include all error messages if any.
    validations:
      required: true
