name: Error message improvement
description: Compiler produces an unhelpful or misleading error message.
labels: ["error message"]
body:
  - type: input
    id: version
    attributes:
      label: Zig Version
      description: "The output of `zig version`"
      placeholder: "0.11.0-dev.146+2897641fb"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce and Observed Output
      description: A complete list of steps to reproduce the error message.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Output
      description: What information do expect the error message to include?
    validations:
      required: true
