# These constants are also in include/structmember.h

T_SHORT = 0
T_INT = 1
T_LONG = 2
T_FLOAT = 3
T_DOUBLE = 4
T_STRING = 5
T_OBJECT = 6
T_CHAR = 7
T_BYTE = 8
T_UBYTE = 9
T_USHORT = 10
T_UINT = 11
T_ULONG = 12
T_STRING_INPLACE = 13
T_BOOL = 14
T_OBJECT_EX = 16
T_LONGLONG = 17
T_ULONGLONG = 18
T_PYSSIZET = 19

READONLY = RO = 1
READ_RESTRICTED = 2
WRITE_RESTRICTED = 4
RESTRICTED = READ_RESTRICTED | WRITE_RESTRICTED
