#!/bin/sh

set -x

export CC=clang-5.0
export CXX=clang++-5.0
which $CC
which $CXX
echo $PATH
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd) -DZIG_LIBC_LIB_DIR=$(dirname $($CC -print-file-name=crt1.o)) -DZIG_LIBC_INCLUDE_DIR=$(echo -n | $CC -E -x c - -v 2>&1 | grep -B1 "End of search list." | head -n1 | cut -c 2- | sed "s/ .*//") -DZIG_LIBC_STATIC_LIB_DIR=$(dirname $($CC -print-file-name=crtbegin.o)) -DZIG_FORCE_EXTERNAL_LLD=ON
make VERBOSE=1
make install
# we have to skip cross compiling OSX tests because apt.llvm.org has an old version
# of llvm for the version of ubuntu that travis is running on.
./zig build --build-file ../build.zig test-behavior test-std test-compiler-rt -Dtest-filter=linux
./zig build --build-file ../build.zig test-compare-output test-build-examples test-compile-errors test-asm-link test-debug-safety test-parsec
