#!/bin/sh

set -x
set -e

mkdir build
cd build
cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@7/ -DCMAKE_BUILD_TYPE=Release
make VERBOSE=1
make install

./zig build --build-file ../build.zig test -Dskip-release-small
