#!/bin/sh

set -x
set -e

sudo pkg update -fq
sudo pkg install -y cmake py39-s3cmd wget curl jq samurai

ZIGDIR="$(pwd)"
TARGET="x86_64-freebsd-gnu"
MCPU="baseline"
CACHE_BASENAME="zig+llvm+lld+clang-$TARGET-0.10.0-dev.3524+74673b7f6"
PREFIX="$HOME/$CACHE_BASENAME"

cd $HOME
wget -nv "https://ziglang.org/deps/$CACHE_BASENAME.tar.xz"
tar xf "$CACHE_BASENAME.tar.xz"

cd $ZIGDIR

# Make the `zig version` number consistent.
# This will affect the cmake command below.
git config core.abbrev 9
git fetch --unshallow || true
git fetch --tags

# SourceHut reports that it is a terminal that supports escape codes, but it
# is a filthy liar. Here we tell Zig to not try to send any terminal escape
# codes to show progress.
export TERM=dumb

mkdir build
cd build
cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_PREFIX_PATH=$PREFIX \
  -DZIG_TARGET_TRIPLE="$TARGET" \
  -DZIG_TARGET_MCPU="$MCPU" \
  -DZIG_STATIC=ON \
  -GNinja
samu install

# TODO: eliminate this workaround. Without this, zig does not end up passing
# -isystem /usr/include when building libc++, resulting in #include <sys/endian.h>
# "file not found" errors.
stage2/bin/zig libc >libc.txt

ZIG_LIBC=libc.txt stage2/bin/zig build \
  --prefix stage3-release \
  --search-prefix "$PREFIX" \
  -Dstatic-llvm \
  -Drelease \
  -Dstrip \
  -Dtarget="$TARGET" \
  -Denable-stage1

# Here we skip some tests to save time.
stage3-release/bin/zig build test docs \
  -Dstatic-llvm \
  --search-prefix "$PREFIX" \
  -Dskip-stage1 \
  -Dskip-non-native

# Produce the experimental std lib documentation.
mkdir -p "stage3-release/doc/std"
stage3-release/bin/zig test lib/std/std.zig \
  --zig-lib-dir lib \
  -femit-docs=stage3-release/doc/std/ \
  -fno-emit-bin

if [ -f ~/.s3cfg ]; then
  # Remove the unnecessary bin dir in stage3-release/bin/zig
  mv stage3-release/bin/zig stage3-release/
  rmdir stage3-release/bin

  # Remove the unnecessary zig dir in stage3-release/lib/zig/std/std.zig
  mv stage3-release/lib/zig stage3-release/lib2
  rmdir stage3-release/lib
  mv stage3-release/lib2 stage3-release/lib

  mv ../LICENSE stage3-release/
  mv ../zig-cache/langref.html stage3-release/doc


  GITBRANCH=$(basename $GITHUB_REF)
  VERSION=$(stage3-release/zig version)
  DIRNAME="zig-freebsd-x86_64-$VERSION"
  TARBALL="$DIRNAME.tar.xz"
  mv stage3-release "$DIRNAME"
  tar cfJ "$TARBALL" "$DIRNAME"

  s3cmd put -P --add-header="cache-control: public, max-age=31536000, immutable" "$TARBALL" s3://ziglang.org/builds/

  SHASUM=$(shasum -a 256 $TARBALL | cut '-d ' -f1)
  BYTESIZE=$(wc -c < $TARBALL)

  JSONFILE="freebsd-$GITBRANCH.json"
  touch $JSONFILE
  echo "{\"tarball\": \"$TARBALL\"," >>$JSONFILE
  echo "\"shasum\": \"$SHASUM\"," >>$JSONFILE
  echo "\"size\": \"$BYTESIZE\"}" >>$JSONFILE

  s3cmd put -P --add-header="Cache-Control: max-age=0, must-revalidate" "$JSONFILE" "s3://ziglang.org/builds/$JSONFILE"
  s3cmd put -P "$JSONFILE" "s3://ziglang.org/builds/x86_64-freebsd-$VERSION.json"

  if [ "$GITBRANCH" = "master" ]; then
    # avoid leaking oauth token
    set +x

    OAUTH_TOKEN="$(cat ~/.oauth_token)"
    cd "$ZIGDIR"
    ./ci/srht/on_master_success "$VERSION" "$OAUTH_TOKEN"
  fi
fi
