#!/bin/sh

set -x
set -e

sudo pkgin -y update
sudo pkgin -y upgrade
sudo pkgin -y install cmake samurai curl jq py27-s3cmd wget clang

ZIGDIR="$(pwd)"
CACHE_BASENAME="zig+llvm+lld+clang-x86_64-netbsd-gnu-0.8.0"
PREFIX="$HOME/$CACHE_BASENAME"

cd $HOME
wget -nv "https://ziglang.org/deps/$CACHE_BASENAME.tar.xz"
tar xf "$CACHE_BASENAME.tar.xz"

cd $ZIGDIR

# Make the `zig version` number consistent.
# This will affect the cmake command below.
git config core.abbrev 9
git fetch --unshallow || true
git fetch --tags

# SourceHut reports that it is a terminal that supports escape codes, but it
# is a filthy liar. Here we tell Zig to not try to send any terminal escape
# codes to show progress.
export TERM=dumb

mkdir build
cd build
export CC="$PREFIX/bin/zigcc"
export CXX="$PREFIX/bin/zigcxx"
echo "#!/bin/sh
env CC=\"clang\" $PREFIX/bin/zig cc \"\$@\"" > $CC
echo "#!/bin/sh
env CC=\"clang\" $PREFIX/bin/zig c++ \"\$@\"" > $CXX
chmod +x $CC
chmod +x $CXX

cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    "-DCMAKE_INSTALL_PREFIX=$(pwd)/release" \
    -DZIG_STATIC=ON \
    -DZIG_TARGET_TRIPLE=x86_64-netbsd-none \
    -GNinja
samu install

unset CC
unset CXX

# TODO ld.lld: error: undefined symbol: main
#>>> referenced by crt0-common.c
#>>>               /usr/lib/crt0.o:(___start)
#release/bin/zig test ../test/behavior.zig -fno-stage1 -fLLVM -I ../test

# Here we skip some tests to save time.
release/bin/zig build test -Dskip-compile-errors -Dskip-non-native

if [ -f ~/.s3cfg ]; then
  mv ../LICENSE release/
  mv ../zig-cache/langref.html release/
  mv release/bin/zig release/
  rmdir release/bin

  GITBRANCH=$(basename $GITHUB_REF)
  VERSION=$(release/zig version)
  DIRNAME="zig-netbsd-x86_64-$VERSION"
  TARBALL="$DIRNAME.tar.xz"
  mv release "$DIRNAME"
  tar cfJ "$TARBALL" "$DIRNAME"

  s3cmd put -P --add-header="cache-control: public, max-age=31536000, immutable" "$TARBALL" s3://ziglang.org/builds/

  SHASUM=$(shasum -a 256 $TARBALL | cut '-d ' -f1)
  BYTESIZE=$(wc -c < $TARBALL)

  JSONFILE="netbsd-$GITBRANCH.json"
  touch $JSONFILE
  echo "{\"tarball\": \"$TARBALL\"," >>$JSONFILE
  echo "\"shasum\": \"$SHASUM\"," >>$JSONFILE
  echo "\"size\": \"$BYTESIZE\"}" >>$JSONFILE

  s3cmd put -P --add-header="Cache-Control: max-age=0, must-revalidate" "$JSONFILE" "s3://ziglang.org/builds/$JSONFILE"
  s3cmd put -P "$JSONFILE" "s3://ziglang.org/builds/x86_64-netbsd-$VERSION.json"

  if [ "$GITBRANCH" = "master" ]; then 
    # avoid leaking oauth token
    set +x

    OAUTH_TOKEN="$(cat ~/.oauth_token)"
    cd "$ZIGDIR"
    ./ci/srht/on_master_success "$VERSION" "$OAUTH_TOKEN"
  fi
fi
