name: ci-pr-riscv64-linux
on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: riscv64-linux-${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read
jobs:
  riscv64-linux-debug:
    if: contains(github.event.pull_request.labels.*.name, 'ci-riscv64-linux')
    timeout-minutes: 420
    runs-on: [self-hosted, Linux, riscv64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: sh ci/riscv64-linux-debug.sh
  riscv64-linux-release:
    if: contains(github.event.pull_request.labels.*.name, 'ci-riscv64-linux')
    timeout-minutes: 420
    runs-on: [self-hosted, Linux, riscv64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: sh ci/riscv64-linux-release.sh
