#!/bin/sh


set -x

uname -a
hostname
cat /proc/meminfo| grep -i ^mem
pwd
df -h $HOME/.
df -h .
ls -al $HOME/.
ls -al .
ulimit -a
env | sort

date
touch $HOME/foo.timestamp
touch ./foo.timestamp
ls --full-time -ld $HOME/foo.timestamp
ls --full-time -ld ./foo.timestamp

date
touch $HOME/foo.timestamp
touch ./foo.timestamp
ls --full-time -ld $HOME/foo.timestamp
ls --full-time -ld ./foo.timestamp

date
touch $HOME/foo.timestamp
touch ./foo.timestamp
ls --full-time -ld $HOME/foo.timestamp
ls --full-time -ld ./foo.timestamp

date

cat /proc/sys/kernel/randomize_va_space

set -e

export ZIG_GLOBAL_CACHE_DIR="$(pwd)/zig-cache"

TRIPLEARCH="$(uname -m)"
BUILDDIR="$(pwd)"
DISTDIR="$(pwd)/dist"

apk update
apk add py3-pip xz perl-utils jq curl samurai
pip3 install s3cmd

apk add util-linux rclone gdb
lscpu

# abort if Falkor
if (lscpu | grep 'Model.*Falkor'); then
    echo "--- ABORT: Falkor detected"
    exit 1
fi

# Make the `zig version` number consistent.
# This will affect the cmake command below.
git config core.abbrev 9
git fetch --unshallow || true
git fetch --tags

mkdir build
cd build
cmake .. -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$DISTDIR" \
    -DZIG_STATIC=ON \
    -DCMAKE_PREFIX_PATH="/deps/local" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

samu install

## what does zig detect
./zig build-obj --show-builtin
./zig build-obj --show-builtin -mcpu=baseline

## what we know about drone hang
## - happens during test
## - doesn't seem to linked to a specific test
## - time between `build test` and first console output ~282s

## enable coredumps
ulimit -c unlimited
ulimit -a
sync

## test_runner has an OOT killer set send SEGV to self-pid at 600s
## test_runner will also create file `core.exename` with path to test

#./zig build test \
#    -Dskip-release \
#    -Dskip-non-native \
#    -Dskip-compile-errors \
#    -Dskip-run-translated-c \
#    -Dlog=true \
#    -Dcpu=baseline \
#    --verbose-cc --verbose-link

#BUILD_TEST_PID=$!
#(sleep 60; echo "--- KILL $BUILD_TEST_PID ---"; kill -SEGV $BUILD_TEST_PID) &

## these are baseline features shown
#   .ete,
#   .fp_armv8,
#   .fuse_aes,
#   .neon,
#   .perfmon,
#   .trbe,
#   .use_postra_scheduler,

#./zig test ../test/stage1/behavior.zig -I ../test -lc -mcpu=baseline
#./zig test ../test/stage1/behavior.zig -I ../test -lc

#./zig test ../lib/std/std.zig -mcpu=baseline
#./zig test ../lib/std/std.zig

# - run inside gdb and if it hangs we have a chance to force SEGV
gdb --batch -ex "r" -ex "thread apply all bt" --args ./zig test ../test/stage1/behavior.zig -I ../test -lc > 'log.zig.txt' 2>&1 &

# give time for background test.exe to build and launch
sleep 120

set +e

PID_TEST=$(pgrep -nx '.*/test')
if [[ -n "$PID_TEST" ]]; then
    if (kill -SEGV "$PID_TEST"); then
        # give time for backtrace
        sleep 30
    fi
fi

PID_ZIG=$(pgrep -nx '.*/zig')
if [[ -n "$PID_ZIG" ]]; then
    if (kill -SEGV "$PID_ZIG"); then
        # give time for backtrace
        sleep 30
    fi
fi

GFOLDER="gdrive:drone.${DRONE_BUILD_NUMBER}"
rclone --config ../gdrive.conf copy 'log.zig.txt' "$GFOLDER"
rclone --config ../gdrive.conf copy $(find ../test/stage1/zig-cache -name test) "$GFOLDER"
rclone --config ../gdrive.conf copy zig "$GFOLDER"

set -e

echo "-----  ALL DONE -----"
echo "-----  ALL DONE -----"
echo "-----  ALL DONE -----"

exit 0

# following this point in script does not work out:
# - it seems that test.exe is finishing so there's never a proc/core to get
# - trying to gdb -p results in permission denied even though we are root
# - probably a container thing

./zig test ../test/stage1/behavior.zig -I ../test -lc > 'log.zig' 2>&1 &
PID_ZIG=$!

set +e

# give time for background test.exe to build and launch
sleep 120

GFOLDER="gdrive:drone.${DRONE_BUILD_NUMBER}"
rclone --config ../gdrive.conf mkdir $GFOLDER

PID_TEST=$(pgrep -ox "test")

# sanity check: is it still running?
pgrep -ox "zig"
pgrep -ox "test"

# pause processes so we may get cores
kill -STOP $PID_ZIG $PID_TEST

if [[ -n "$PID_TEST" ]]; then
    if (kill -STOP "$PID_TEST"); then
        gdb -batch -p "$PID_TEST" -ex 'thread apply all bt' > 'log.gdb.test' 2>&1
        rclone --config ../gdrive.conf copy 'log.gdb.test' $GFOLDER
        kill -SEGV "$PID_TEST"
        # give time for core file to dump
        sleep 30
        if [[ -f core ]]; then
            rclone --config ../gdrive.conf copyto core "$GFOLDER/core.test"
            rm core
        fi
    fi
fi

if [[ -n "$PID_ZIG" ]]; then
    if (kill -STOP "$PID_ZIG"); then
        gdb -batch -p "$PID_ZIG" -ex 'thread apply all bt' > 'log.gdb.zig' 2>&1
        rclone --config ../gdrive.conf copy 'log.gdb.zig' $GFOLDER
        kill -SEGV "$PID_ZIG"
        # give time for core file to dump
        sleep 30
        if [[ -f core ]]; then
            rclone --config ../gdrive.conf copyto core "$GFOLDER/core.zig"
            rm core
        fi
    fi
fi

rclone --config ../gdrive.conf copy 'log.zig' $GFOLDER
rclone --config ../gdrive.conf copy $(find ../test/stage1/zig-cache -name test) $GFOLDER
rclone --config ../gdrive.conf copy zig $GFOLDER

set -e

echo "-----  ALL DONE -----"
echo "-----  ALL DONE -----"
echo "-----  ALL DONE -----"

exit 0

## now if we had a test hang, there should be "core" in cwd
#gdb -batch -ex "thread 1" -ex "bt" `cat core.exename` core

if [ -z "$DRONE_PULL_REQUEST" ]; then
  mv ../LICENSE "$DISTDIR/"
  mv ../zig-cache/langref.html "$DISTDIR/"
  mv "$DISTDIR/bin/zig" "$DISTDIR/"
  rmdir "$DISTDIR/bin"

  GITBRANCH="$DRONE_BRANCH"
  VERSION="$("$DISTDIR/zig" version)"
  DIRNAME="zig-linux-$TRIPLEARCH-$VERSION"
  TARBALL="$DIRNAME.tar.xz"
  mv "$DISTDIR" "$DIRNAME"
  tar cfJ "$TARBALL" "$DIRNAME"

  s3cmd put -P --add-header="cache-control: public, max-age=31536000, immutable" "$TARBALL" s3://ziglang.org/builds/

  SHASUM=$(shasum -a 256 $TARBALL | cut '-d ' -f1)
  BYTESIZE=$(wc -c < $TARBALL)

  JSONFILE="$TRIPLEARCH-linux-$GITBRANCH.json"
  touch $JSONFILE
  echo "{\"tarball\": \"$TARBALL\"," >>$JSONFILE
  echo "\"shasum\": \"$SHASUM\"," >>$JSONFILE
  echo "\"size\": \"$BYTESIZE\"}" >>$JSONFILE

  s3cmd put -P --add-header="Cache-Control: max-age=0, must-revalidate" "$JSONFILE" "s3://ziglang.org/builds/$JSONFILE"
  s3cmd put -P "$JSONFILE" "s3://ziglang.org/builds/$TRIPLEARCH-linux-$VERSION.json"
  if [ "$GITBRANCH" = "master" ]; then 
    # avoid leaking oauth token
    set +x

    cd "$BUILDDIR"
    ./ci/srht/on_master_success "$VERSION" "$SRHT_OAUTH_TOKEN"
  fi
fi
