#!/bin/sh

set -x
set -e

INSTALL_PREFIX="$DRONE_WORKSPACE/stage3-release"
ZIG="$INSTALL_PREFIX/bin/zig"
export ZIG_GLOBAL_CACHE_DIR="$DRONE_WORKSPACE/zig-cache"

$ZIG build test-compiler-rt    -Dskip-non-native --zig-lib-dir lib
$ZIG build test-compare-output -Dskip-non-native --zig-lib-dir lib
$ZIG build test-universal-libc -Dskip-non-native --zig-lib-dir lib
$ZIG build test-stack-traces   -Dskip-non-native --zig-lib-dir lib
$ZIG build test-cli            -Dskip-non-native --zig-lib-dir lib
$ZIG build test-asm-link       -Dskip-non-native --zig-lib-dir lib
$ZIG build test-translate-c    -Dskip-non-native --zig-lib-dir lib
$ZIG build test-fmt                              --zig-lib-dir lib
