#!/bin/sh

set -x
set -e

INSTALL_PREFIX="$DRONE_WORKSPACE/stage3-release"
ZIG="$INSTALL_PREFIX/bin/zig"
export ZIG_GLOBAL_CACHE_DIR="$DRONE_WORKSPACE/zig-cache"

$ZIG build test-std \
  --zig-lib-dir lib \
  -Dskip-release-safe \
  -Dskip-release-fast \
  -Dskip-release-small \
  -Dskip-non-native

# Produce the experimental std lib documentation.
mkdir -p "$INSTALL_PREFIX/doc/std"
$ZIG test "$DRONE_WORKSPACE/lib/std/std.zig" \
  --zig-lib-dir "$DRONE_WORKSPACE/lib" \
  -femit-docs="$INSTALL_PREFIX/doc/std" \
  -fno-emit-bin
